CREATE DATABASE customer_behaviour;
USE customer_behaviour;

DESCRIBE customer;
SELECT * FROM customer;

SELECT COUNT(*) FROM customer;
##total no of revenue generated by male vs female
SELECT gender,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender; 

##which customers used a discount but still spent more than avg purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='YES' AND purchase_amount>=(SELECT  AVG(purchase_amount) FROM customer);

##which are the top 5 products with highest avg review rating
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

##4) compare the avg Purchase Amount between Standard and Express Shipping
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

##5) do subscribed customers spend more? compare avg spend and total revenue bet subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

##6)which 5 products have the highest % of puchases with discounts applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied ='YES' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

##7)segment customers into new, returning and loyal based on their total number of prebious purchases,and show the count of each segment
SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 4 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment;

##8)what are the top 3 most purchased_products within each category
SELECT category, item_purchased, total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rank_in_category <= 3;

##9)are customers who are repeat buyers more then 5 previous purchases also likely to subscriber
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;

##10)what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;



